# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker info

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

build:
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE" .
  only:
    - master

build-docker:
  stage: build
  script:
    - docker build --pull -t $DOCKER_REGISTRY_IMAGE .
  only:
    - master

registry-local:
  stage: build
  before_script:
    - echo "$CI_REGISTRY_USER - $CI_REGISTRY_PASSWORD - $CI_REGISTRY - $CI_REGISTRY_IMAGE"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

registry-docker:
  stage: build
  before_script:
    - echo "$DOCKER_REGISTRY_USER - $DOCKER_REGISTRY_PASSWORD - $DOCKER_REGISTRY_IMAGE"
    - docker login index.docker.io -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
  script:
    - docker push $DOCKER_REGISTRY_IMAGE

deploy:
  stage: deploy
  script:
    - apk add --update curl
    - curl -H "X-Docker-Token:$DOCKER_AUTH_TOKEN"  -X GET "https://siliconspirit.net/hooks/docker-iot-update?DOCKER_SERVICE_NAME=automation_$CI_PROJECT_NAME&DOCKER_IMAGE_PREFIX=$DOCKER_REGISTRY_USER&DOCKER_IMAGE_NAME=$CI_PROJECT_NAME&DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG"